# Generated by Django 5.2.17 on 2026-08-24 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_historicalcustomer'),
        ('organizations', '0001_initial'),
        ('sales', '0002_historicallead_historicalquotation_and_more'),
        ('vehicles', '0002_historicalvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('sale',), name='unique_invoice_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('vehicle',), name='one_active_reservation_per_vehicle'),
        ),
    ]
