# Generated by Django 5.2.17 on 2026-09-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('sales', '0005_add_crm_fields_to_historical_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Branch where this lead was captured or is being managed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='name',
            field=models.CharField(help_text='Lead or prospect name.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='notes',
            field=models.TextField(blank=True, help_text='Lead notes, follow-up summary, and key buying intent details.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='phone',
            field=models.CharField(blank=True, help_text='Best phone number or WhatsApp contact for this lead.', max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Quoted selling price in the selected currency.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', help_text='Currency used for the quotation and any linked reservation.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='notes',
            field=models.TextField(blank=True, help_text='Terms, customer preferences, or negotiation details for this quote.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', help_text='Commercial status of this quotation.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalquotation',
            name='valid_until',
            field=models.DateField(help_text='Deadline for acceptance of this quote.', verbose_name='valid until'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', help_text='Currency of the reservation deposit and vehicle value.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, help_text='Temporary hold amount requested from the customer.', max_digits=14, verbose_name='deposit amount'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='notes',
            field=models.TextField(blank=True, help_text='Reservation terms, conditions, or internal notes.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalreservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Current state of the reservation.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this lead was captured or is being managed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(help_text='Lead or prospect name.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, help_text='Lead notes, follow-up summary, and key buying intent details.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, help_text='Best phone number or WhatsApp contact for this lead.', max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Quoted selling price in the selected currency.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', help_text='Currency used for the quotation and any linked reservation.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, help_text='Terms, customer preferences, or negotiation details for this quote.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='draft', help_text='Commercial status of this quotation.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(help_text='Deadline for acceptance of this quote.', verbose_name='valid until'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', help_text='Currency of the reservation deposit and vehicle value.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, help_text='Temporary hold amount requested from the customer.', max_digits=14, verbose_name='deposit amount'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, help_text='Reservation terms, conditions, or internal notes.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Current state of the reservation.', max_length=20, verbose_name='status'),
        ),
    ]
