# Generated by Django 5.2.17 on 2026-09-02 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_branch_alter_customer_email_and_more'),
        ('organizations', '0001_initial'),
        ('sales', '0006_alter_historicallead_branch_and_more'),
        ('vehicles', '0005_alter_historicalvehicle_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalreservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', help_text='Current state of the reservation.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', help_text='Current state of the reservation.', max_length=20, verbose_name='status'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('vehicle',), name='one_completed_sale_per_vehicle'),
        ),
    ]
