# Generated by Django 5.2.17 on 2026-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_keep_sale_uniqueness_database_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Date by which the customer is expected to settle the invoice.', null=True, verbose_name='due date'),
        ),
    ]
