# Generated by Django 5.2.17 on 2026-09-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0002_historicalcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch or showroom assigned to this customer record.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Official email address for communication and invoices.', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='full_name',
            field=models.CharField(help_text='Primary customer name as shown on documents and sales records.', max_length=200, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID, passport number, or Tazkera reference.', max_length=50, verbose_name='national ID'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, preferences, or anything useful for sales follow-up.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, help_text='Best contact number for calls, WhatsApp, and follow-up.', max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Branch or showroom assigned to this customer record.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, help_text='Official email address for communication and invoices.', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='full_name',
            field=models.CharField(help_text='Primary customer name as shown on documents and sales records.', max_length=200, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID, passport number, or Tazkera reference.', max_length=50, verbose_name='national ID'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, preferences, or anything useful for sales follow-up.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone',
            field=models.CharField(blank=True, help_text='Best contact number for calls, WhatsApp, and follow-up.', max_length=50, verbose_name='phone'),
        ),
    ]
