# Generated by Django 5.2.17 on 2026-08-18 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_historicalcustomer'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messenger', 'Messenger'), ('instagram', 'Instagram'), ('telegram', 'Telegram'), ('email', 'Email'), ('sms', 'SMS')], max_length=20, verbose_name='type')),
                ('credentials', models.JSONField(blank=True, default=dict, verbose_name='credentials')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_thread_id', models.CharField(blank=True, max_length=255, verbose_name='external thread id')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='status')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='last message at')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL, verbose_name='assigned to')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='communications.channel', verbose_name='channel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerChannelIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='external id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identities', to='communications.channel', verbose_name='channel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_identities', to='customers.customer', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'customer channel identity',
                'verbose_name_plural': 'customer channel identities',
                'constraints': [models.UniqueConstraint(fields=('company', 'channel', 'external_id'), name='unique_external_id_per_channel')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=5, verbose_name='direction')),
                ('body', models.TextField(verbose_name='body')),
                ('media', models.JSONField(blank=True, default=list, verbose_name='media')),
                ('external_message_id', models.CharField(blank=True, max_length=255, verbose_name='external message id')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('skipped_disabled', 'Skipped (integration disabled)')], default='queued', max_length=20, verbose_name='status')),
                ('raw_payload', models.JSONField(blank=True, null=True, verbose_name='raw payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communications.conversation', verbose_name='conversation')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_message_id', ''), _negated=True), fields=('company', 'external_message_id'), name='unique_external_message_per_company')],
            },
        ),
    ]
