# Generated by Django 5.2.17 on 2026-08-18 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_historicalcustomer'),
        ('organizations', '0001_initial'),
        ('vehicles', '0002_historicalvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('vehicle_photo', 'Vehicle photo'), ('vehicle_document', 'Vehicle document'), ('customer_document', 'Customer document'), ('other', 'Other')], default='other', max_length=30, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='customers.customer', verbose_name='customer')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
