# Generated by Django 5.2.17 on 2026-08-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('vehicle_photo', 'Vehicle photo'), ('license', 'Vehicle license'), ('sale_document', 'Sale document'), ('insurance', 'Insurance policy'), ('customs', 'Customs / import document'), ('inspection', 'Inspection report'), ('vehicle_document', 'Other vehicle document'), ('customer_document', 'Customer document'), ('other', 'Other')], default='other', max_length=30, verbose_name='type'),
        ),
    ]
