# Generated by Django 5.2.17 on 2026-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_supplier_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('vehicle_photo', 'Vehicle photo'), ('license', 'Vehicle license'), ('sale_document', 'Sale document'), ('insurance', 'Insurance policy'), ('customs', 'Customs / import document'), ('inspection', 'Inspection report'), ('vehicle_document', 'Other vehicle document'), ('customer_photo', 'Customer photo'), ('tazkera', 'Tazkera (national ID)'), ('passport', 'Passport'), ('electricity_bill', 'Electricity bill'), ('other_bill', 'Other bill'), ('customer_document', 'Other customer document'), ('supplier_logo', 'Supplier logo / photo'), ('supplier_photo', 'Supplier portrait photo'), ('supplier_license', 'Supplier business license'), ('supplier_document', 'Other supplier document'), ('other', 'Other')], default='other', max_length=30, verbose_name='type'),
        ),
    ]
