# Generated by Django 5.2.17 on 2026-08-24 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_historicalcustomer'),
        ('documents', '0005_alter_document_doc_type'),
        ('organizations', '0001_initial'),
        ('suppliers', '0004_historicalsupplier_kind_and_more'),
        ('vehicles', '0002_historicalvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('supplier__isnull', True), ('vehicle__isnull', False)), models.Q(('customer__isnull', False), ('supplier__isnull', True), ('vehicle__isnull', True)), models.Q(('customer__isnull', True), ('supplier__isnull', False), ('vehicle__isnull', True)), _connector='OR'), name='document_exactly_one_target'),
        ),
    ]
