# Generated by Django 5.2.17 on 2026-08-18 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer_payment', 'Customer payment'), ('supplier_payment', 'Supplier payment'), ('expense', 'Expense'), ('other', 'Other')], max_length=30, verbose_name='type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', max_length=3, verbose_name='currency')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='related object id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name='related object type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='payments.ledgerentry', verbose_name='reversal of')),
            ],
            options={
                'verbose_name': 'ledger entry',
                'verbose_name_plural': 'ledger entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
