# Generated by Django 5.2.17 on 2026-08-24 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('reversal_of__isnull', False)), fields=('reversal_of',), name='one_reversal_per_ledger_entry'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_entry_amount_positive'),
        ),
    ]
