# Generated by Django 5.2.17 on 2026-08-30 17:48

import apps.core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0002_historicalcustomer'),
        ('organizations', '0001_initial'),
        ('payments', '0002_ledgerentry_one_reversal_per_ledger_entry_and_more'),
        ('purchases', '0005_purchaseorderline_po_line_amount_positive_and_more'),
        ('sales', '0003_invoice_unique_invoice_per_sale_and_more'),
        ('suppliers', '0004_historicalsupplier_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('CARD', 'Card'), ('CHECK', 'Check'), ('MOBILE_MONEY', 'Mobile money'), ('OTHER', 'Other')], default='OTHER', max_length=20, verbose_name='payment method'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='purchases.purchaseorder', verbose_name='purchase order'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='receipt number'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='reference'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='sales.reservation', verbose_name='reservation'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='sales.sale', verbose_name='sale'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='suppliers.supplier', verbose_name='supplier'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today, verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('customer_payment', 'Customer payment'), ('supplier_payment', 'Supplier payment'), ('expense', 'Expense'), ('refund', 'Refund'), ('other_in', 'Other inflow'), ('other_out', 'Other outflow'), ('other', 'Other')], max_length=30, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='account type')),
                ('currency', models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', max_length=3, verbose_name='currency')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='branches.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
            ],
            options={
                'verbose_name': 'financial account',
                'verbose_name_plural': 'financial accounts',
                'ordering': ['name'],
            },
            bases=(apps.core.models.CompanyConsistencyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.financialaccount', verbose_name='financial account'),
        ),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_financial_account_name_per_company'),
        ),
    ]
