# Generated by Django 5.2.17 on 2026-08-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('expenses', '0001_initial'),
        ('payments', '0003_ledgerentry_customer_ledgerentry_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='expenses.expensecategory', verbose_name='expense category'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, verbose_name='vendor / payee'),
        ),
    ]
