# Generated by Django 5.2.17 on 2026-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_ledgersequence_unique_receipts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='type',
            field=models.CharField(choices=[('customer_payment', 'Customer payment'), ('supplier_payment', 'Supplier payment'), ('expense', 'Expense'), ('refund', 'Refund'), ('lender_disbursement', 'Lender disbursement'), ('other_in', 'Other inflow'), ('other_out', 'Other outflow'), ('other', 'Other')], max_length=30, verbose_name='type'),
        ),
    ]
