# Generated by Django 5.2.17 on 2026-08-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, verbose_name='VIN')),
                ('make', models.CharField(max_length=100, verbose_name='make')),
                ('model', models.CharField(max_length=100, verbose_name='model')),
                ('year', models.PositiveSmallIntegerField(verbose_name='year')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='color')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='mileage (km)')),
                ('status', models.CharField(choices=[('in_transit', 'In transit'), ('in_stock', 'In stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('delivered', 'Delivered')], default='in_transit', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='branches.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'vin'), name='unique_vin_per_company')],
            },
        ),
    ]
