# Generated by Django 5.2.17 on 2026-08-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_historicalvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In transit'), ('in_stock', 'In stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('delivered', 'Delivered')], default='in_transit', help_text='Deprecated: the authoritative inventory state lives on inventory.VehicleStock.status (§8). Do not use.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In transit'), ('in_stock', 'In stock'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('delivered', 'Delivered')], default='in_transit', help_text='Deprecated: the authoritative inventory state lives on inventory.VehicleStock.status (§8). Do not use.', max_length=20, verbose_name='status'),
        ),
    ]
