# Generated by Django 5.2.17 on 2026-08-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_historicalvehicle_status_alter_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('van', 'Van'), ('coupe', 'Coupe'), ('truck', 'Truck'), ('other', 'Other')], default='other', help_text='Vehicle body style.', max_length=20, verbose_name='body type'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='chassis_number',
            field=models.CharField(blank=True, help_text='Chassis or frame number.', max_length=100, verbose_name='chassis number'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='Country where the vehicle was built or imported from.', max_length=5, verbose_name='country of origin'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='door_count',
            field=models.PositiveSmallIntegerField(blank=True, default=4, help_text='Number of doors.', verbose_name='door count'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-wheel drive'), ('rwd', 'Rear-wheel drive'), ('awd', 'All-wheel drive'), ('4x4', '4x4'), ('other', 'Other')], default='fwd', help_text='Drive configuration.', max_length=20, verbose_name='drive type'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='engine_number',
            field=models.CharField(blank=True, help_text='Engine serial or identification number.', max_length=100, verbose_name='engine number'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, help_text='Date of first registration, if known.', null=True, verbose_name='first registration date'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG'), ('other', 'Other')], default='petrol', help_text='Primary fuel or energy type.', max_length=20, verbose_name='fuel type'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='model_variant',
            field=models.CharField(blank=True, help_text='Trim, variant, or package name.', max_length=100, verbose_name='model variant'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Current registration plate or number plate.', max_length=50, verbose_name='plate number'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Official registration or document reference.', max_length=100, verbose_name='registration number'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='seating_capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=5, help_text='Passenger seating capacity.', verbose_name='seating capacity'),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('dual_clutch', 'Dual clutch'), ('other', 'Other')], default='automatic', help_text='Transmission type.', max_length=20, verbose_name='transmission'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('van', 'Van'), ('coupe', 'Coupe'), ('truck', 'Truck'), ('other', 'Other')], default='other', help_text='Vehicle body style.', max_length=20, verbose_name='body type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, help_text='Chassis or frame number.', max_length=100, verbose_name='chassis number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='Country where the vehicle was built or imported from.', max_length=5, verbose_name='country of origin'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='door_count',
            field=models.PositiveSmallIntegerField(blank=True, default=4, help_text='Number of doors.', verbose_name='door count'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drive_type',
            field=models.CharField(blank=True, choices=[('fwd', 'Front-wheel drive'), ('rwd', 'Rear-wheel drive'), ('awd', 'All-wheel drive'), ('4x4', '4x4'), ('other', 'Other')], default='fwd', help_text='Drive configuration.', max_length=20, verbose_name='drive type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(blank=True, help_text='Engine serial or identification number.', max_length=100, verbose_name='engine number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, help_text='Date of first registration, if known.', null=True, verbose_name='first registration date'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('lpg', 'LPG'), ('other', 'Other')], default='petrol', help_text='Primary fuel or energy type.', max_length=20, verbose_name='fuel type'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_variant',
            field=models.CharField(blank=True, help_text='Trim, variant, or package name.', max_length=100, verbose_name='model variant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, help_text='Current registration plate or number plate.', max_length=50, verbose_name='plate number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Official registration or document reference.', max_length=100, verbose_name='registration number'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seating_capacity',
            field=models.PositiveSmallIntegerField(blank=True, default=5, help_text='Passenger seating capacity.', verbose_name='seating capacity'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('cvt', 'CVT'), ('dual_clutch', 'Dual clutch'), ('other', 'Other')], default='automatic', help_text='Transmission type.', max_length=20, verbose_name='transmission'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='vin',
            field=models.CharField(help_text='17-character vehicle identification number.', max_length=17, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(help_text='17-character vehicle identification number.', max_length=17, verbose_name='VIN'),
        ),
    ]
