# Generated by Django 5.2.17 on 2026-09-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('vehicles', '0004_historicalvehicle_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Branch where this vehicle is assigned or stored.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Vehicle paint or body color.', max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='make',
            field=models.CharField(help_text='Manufacturer or brand of the vehicle.', max_length=100, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=0, help_text='Current odometer reading in kilometers.', verbose_name='mileage (km)'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='model',
            field=models.CharField(help_text='Vehicle model name or series.', max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, condition comments, or handling details.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Model year as shown on the vehicle registration.', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this vehicle is assigned or stored.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, help_text='Vehicle paint or body color.', max_length=50, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(help_text='Manufacturer or brand of the vehicle.', max_length=100, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=0, help_text='Current odometer reading in kilometers.', verbose_name='mileage (km)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(help_text='Vehicle model name or series.', max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, condition comments, or handling details.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Model year as shown on the vehicle registration.', verbose_name='year'),
        ),
    ]
