# Generated by Django 5.2.17 on 2026-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_historicalsupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], max_length=5, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='supplier_type',
            field=models.CharField(choices=[('local_dealer', 'Local dealer'), ('overseas_dealer', 'Overseas dealer'), ('auction', 'Auction house'), ('broker', 'Broker / agent'), ('shipping_agent', 'Shipping / clearing agent'), ('other', 'Other')], default='local_dealer', max_length=20, verbose_name='supplier type'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], max_length=5, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('local_dealer', 'Local dealer'), ('overseas_dealer', 'Overseas dealer'), ('auction', 'Auction house'), ('broker', 'Broker / agent'), ('shipping_agent', 'Shipping / clearing agent'), ('other', 'Other')], default='local_dealer', max_length=20, verbose_name='supplier type'),
        ),
    ]
