# Generated by Django 5.2.17 on 2026-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_historicalsupplier_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsupplier',
            name='kind',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual (person)')], default='business', max_length=20, verbose_name='kind'),
        ),
        migrations.AddField(
            model_name='historicalsupplier',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='tazkera / national ID no.'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='kind',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual (person)')], default='business', max_length=20, verbose_name='kind'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='tazkera / national ID no.'),
        ),
    ]
