# Generated by Django 5.2.17 on 2026-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_historicalsupplier_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupplier',
            name='address',
            field=models.TextField(blank=True, help_text='Supplier address, office, or showroom location.', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Main person to contact for pricing, follow-up, and documents.', max_length=200, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], help_text='Primary country associated with the supplier or office.', max_length=5, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Official email address for invoices, confirmations, and documents.', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='kind',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual (person)')], default='business', help_text='Choose whether this supplier is a business or a private individual.', max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='name',
            field=models.CharField(help_text='Full supplier name as shown on invoices, purchase paperwork, and official records.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID, passport number, or Tazkera for individual sellers.', max_length=50, verbose_name='tazkera / national ID no.'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, special terms, or business relationship details.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Best direct contact number for supplier communication.', max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='historicalsupplier',
            name='supplier_type',
            field=models.CharField(choices=[('local_dealer', 'Local dealer'), ('overseas_dealer', 'Overseas dealer'), ('auction', 'Auction house'), ('broker', 'Broker / agent'), ('shipping_agent', 'Shipping / clearing agent'), ('other', 'Other')], default='local_dealer', help_text='Select the supplier category used in your sourcing workflow.', max_length=20, verbose_name='supplier type'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Supplier address, office, or showroom location.', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Main person to contact for pricing, follow-up, and documents.', max_length=200, verbose_name='contact person'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], help_text='Primary country associated with the supplier or office.', max_length=5, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Official email address for invoices, confirmations, and documents.', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='kind',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual (person)')], default='business', help_text='Choose whether this supplier is a business or a private individual.', max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(help_text='Full supplier name as shown on invoices, purchase paperwork, and official records.', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID, passport number, or Tazkera for individual sellers.', max_length=50, verbose_name='tazkera / national ID no.'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes, special terms, or business relationship details.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Best direct contact number for supplier communication.', max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('local_dealer', 'Local dealer'), ('overseas_dealer', 'Overseas dealer'), ('auction', 'Auction house'), ('broker', 'Broker / agent'), ('shipping_agent', 'Shipping / clearing agent'), ('other', 'Other')], default='local_dealer', help_text='Select the supplier category used in your sourcing workflow.', max_length=20, verbose_name='supplier type'),
        ),
    ]
