# Generated by Django 5.2.17 on 2026-08-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('in_preparation', 'In preparation')], default='available', max_length=20, verbose_name='status')),
                ('lot_code', models.CharField(blank=True, max_length=50, verbose_name='lot / parking code')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='branches.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
            ],
            options={
                'verbose_name': 'vehicle stock',
                'verbose_name_plural': 'vehicle stock',
                'ordering': ['-received_at'],
            },
        ),
    ]
