# Generated by Django 5.2.17 on 2026-08-18 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestock',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock', to='vehicles.vehicle', verbose_name='vehicle'),
        ),
    ]
