# Generated by Django 5.2.17 on 2026-08-24 13:52

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('inventory', '0003_historicalvehiclestock'),
        ('organizations', '0001_initial'),
        ('vehicles', '0002_historicalvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='available at'),
        ),
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('needs_repair', 'Needs repair')], default='new', max_length=20, verbose_name='condition'),
        ),
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered at'),
        ),
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reserved at'),
        ),
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sold at'),
        ),
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='available_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='available at'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('damaged', 'Damaged'), ('needs_repair', 'Needs repair')], default='new', max_length=20, verbose_name='condition'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='delivered at'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='reserved at'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='sold_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='sold at'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='historicalvehiclestock',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='received at'),
        ),
        migrations.AlterField(
            model_name='historicalvehiclestock',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In transit'), ('received', 'Received'), ('inspection', 'Inspection'), ('preparation', 'Preparation'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('delivered', 'Delivered')], default='received', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='vehiclestock',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='received at'),
        ),
        migrations.AlterField(
            model_name='vehiclestock',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In transit'), ('received', 'Received'), ('inspection', 'Inspection'), ('preparation', 'Preparation'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('delivered', 'Delivered')], default='received', max_length=20, verbose_name='status'),
        ),
        migrations.CreateModel(
            name='HistoricalInventoryLocation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('showroom', 'Showroom'), ('warehouse', 'Warehouse'), ('yard', 'Yard'), ('workshop', 'Workshop'), ('inspection', 'Inspection'), ('lot', 'Lot'), ('other', 'Other')], default='other', max_length=20, verbose_name='type')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='code')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='created at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='branch')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.organization', verbose_name='company')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inventory location',
                'verbose_name_plural': 'historical inventory locations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('type', models.CharField(choices=[('showroom', 'Showroom'), ('warehouse', 'Warehouse'), ('yard', 'Yard'), ('workshop', 'Workshop'), ('inspection', 'Inspection'), ('lot', 'Lot'), ('other', 'Other')], default='other', max_length=20, verbose_name='type')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='code')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='branches.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
            ],
            options={
                'verbose_name': 'inventory location',
                'verbose_name_plural': 'inventory locations',
                'ordering': ['branch__name', 'name'],
            },
            bases=(apps.core.models.CompanyConsistencyMixin, models.Model),
        ),
        migrations.AddField(
            model_name='historicalvehiclestock',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory.inventorylocation', verbose_name='location'),
        ),
        migrations.AddField(
            model_name='vehiclestock',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock', to='inventory.inventorylocation', verbose_name='location'),
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receive', 'Receive'), ('transfer', 'Transfer'), ('move', 'Move'), ('reserve', 'Reserve'), ('release', 'Release'), ('sale', 'Sale'), ('delivery', 'Delivery'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=20, verbose_name='movement type')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='moved at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch', verbose_name='from branch')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventorylocation', verbose_name='from location')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='performed by')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='branches.branch', verbose_name='to branch')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventorylocation', verbose_name='to location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='vehicles.vehicle', verbose_name='vehicle')),
            ],
            options={
                'verbose_name': 'inventory movement',
                'verbose_name_plural': 'inventory movements',
                'ordering': ['-moved_at', '-id'],
            },
            bases=(apps.core.models.CompanyConsistencyMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='inventorylocation',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'branch', 'code'), name='unique_location_code_per_branch'),
        ),
    ]
