# Generated by Django 5.2.17 on 2026-08-18 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', max_length=3, verbose_name='currency')),
            ],
            options={
                'verbose_name': 'purchase order line',
                'verbose_name_plural': 'purchase order lines',
            },
        ),
        migrations.CreateModel(
            name='VehicleCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('purchase', 'Purchase price'), ('transport', 'Transport'), ('customs', 'Customs & duties'), ('storage', 'Storage'), ('repair', 'Repair & preparation'), ('other', 'Other')], max_length=20, verbose_name='cost type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', max_length=3, verbose_name='currency')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'vehicle cost line',
                'verbose_name_plural': 'vehicle cost lines',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='reference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('order_date', models.DateField(verbose_name='order date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='branches.branch', verbose_name='branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'purchase order',
                'verbose_name_plural': 'purchase orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
