# Generated by Django 5.2.17 on 2026-08-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_historicalpurchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='bill_of_lading_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='bill of lading no.'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='container_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='container no.'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='expected arrival'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], max_length=10, verbose_name='incoterms'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], max_length=5, verbose_name='origin country'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('domestic', 'Domestic purchase'), ('import', 'Import from abroad')], default='domestic', max_length=20, verbose_name='purchase type'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='shipped_date',
            field=models.DateField(blank=True, null=True, verbose_name='shipped date'),
        ),
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('container', 'Container (sea)'), ('ro_ro', 'Ro-Ro vessel'), ('land', 'Land transport'), ('air', 'Air freight'), ('other', 'Other')], max_length=20, verbose_name='shipping method'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='bill_of_lading_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='bill of lading no.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='container_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='container no.'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='eta',
            field=models.DateField(blank=True, null=True, verbose_name='expected arrival'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], max_length=10, verbose_name='incoterms'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], max_length=5, verbose_name='origin country'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('domestic', 'Domestic purchase'), ('import', 'Import from abroad')], default='domestic', max_length=20, verbose_name='purchase type'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipped_date',
            field=models.DateField(blank=True, null=True, verbose_name='shipped date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('container', 'Container (sea)'), ('ro_ro', 'Ro-Ro vessel'), ('land', 'Land transport'), ('air', 'Air freight'), ('other', 'Other')], max_length=20, verbose_name='shipping method'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('shipped', 'In transit'), ('customs', 'At customs'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('shipped', 'In transit'), ('customs', 'At customs'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
