# Generated by Django 5.2.17 on 2026-08-24 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('purchases', '0004_historicalpurchaseorder_bill_of_lading_no_and_more'),
        ('vehicles', '0002_historicalvehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='po_line_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='vehiclecostline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='vehicle_cost_line_amount_positive'),
        ),
    ]
