# Generated by Django 5.2.17 on 2026-09-01 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('purchases', '0005_purchaseorderline_po_line_amount_positive_and_more'),
        ('suppliers', '0005_alter_historicalsupplier_address_and_more'),
        ('vehicles', '0004_historicalvehicle_body_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='bill_of_lading_no',
            field=models.CharField(blank=True, help_text='Bill of lading or shipment document reference.', max_length=100, verbose_name='bill of lading no.'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Branch that will receive and manage these vehicles.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='container_no',
            field=models.CharField(blank=True, help_text='Container identification number if the shipment uses containers.', max_length=100, verbose_name='container no.'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='eta',
            field=models.DateField(blank=True, help_text='Expected arrival date for the shipment at your branch.', null=True, verbose_name='expected arrival'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], help_text='Shipping term agreed with the supplier for the shipment.', max_length=10, verbose_name='incoterms'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional import, shipping, or ordering notes for the team.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='order_date',
            field=models.DateField(help_text='Date the order was placed.', verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], help_text='Country of origin for imported vehicles.', max_length=5, verbose_name='origin country'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('domestic', 'Domestic purchase'), ('import', 'Import from abroad')], default='domestic', help_text='Choose whether this order is domestic or imported from abroad.', max_length=20, verbose_name='purchase type'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='reference',
            field=models.CharField(blank=True, help_text='Internal purchase reference or supplier order number.', max_length=50, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='shipped_date',
            field=models.DateField(blank=True, help_text='Date the cargo was dispatched from the supplier.', null=True, verbose_name='shipped date'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('container', 'Container (sea)'), ('ro_ro', 'Ro-Ro vessel'), ('land', 'Land transport'), ('air', 'Air freight'), ('other', 'Other')], help_text='Mode of transportation used for the order.', max_length=20, verbose_name='shipping method'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('shipped', 'In transit'), ('customs', 'At customs'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', help_text='Current state of the purchase workflow.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='historicalpurchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supplier that is selling the vehicles in this order.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='suppliers.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='bill_of_lading_no',
            field=models.CharField(blank=True, help_text='Bill of lading or shipment document reference.', max_length=100, verbose_name='bill of lading no.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch that will receive and manage these vehicles.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='branches.branch', verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='container_no',
            field=models.CharField(blank=True, help_text='Container identification number if the shipment uses containers.', max_length=100, verbose_name='container no.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='eta',
            field=models.DateField(blank=True, help_text='Expected arrival date for the shipment at your branch.', null=True, verbose_name='expected arrival'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CFR', 'CFR'), ('CIF', 'CIF'), ('DAP', 'DAP'), ('DDP', 'DDP')], help_text='Shipping term agreed with the supplier for the shipment.', max_length=10, verbose_name='incoterms'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional import, shipping, or ordering notes for the team.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateField(help_text='Date the order was placed.', verbose_name='order date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='origin_country',
            field=models.CharField(blank=True, choices=[('AF', 'Afghanistan'), ('AE', 'United Arab Emirates'), ('US', 'United States'), ('CA', 'Canada'), ('DE', 'Germany'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('QA', 'Qatar'), ('KW', 'Kuwait'), ('IN', 'India'), ('RU', 'Russia'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('AU', 'Australia'), ('OTHER', 'Other')], help_text='Country of origin for imported vehicles.', max_length=5, verbose_name='origin country'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('domestic', 'Domestic purchase'), ('import', 'Import from abroad')], default='domestic', help_text='Choose whether this order is domestic or imported from abroad.', max_length=20, verbose_name='purchase type'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='reference',
            field=models.CharField(blank=True, help_text='Internal purchase reference or supplier order number.', max_length=50, verbose_name='reference'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipped_date',
            field=models.DateField(blank=True, help_text='Date the cargo was dispatched from the supplier.', null=True, verbose_name='shipped date'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('container', 'Container (sea)'), ('ro_ro', 'Ro-Ro vessel'), ('land', 'Land transport'), ('air', 'Air freight'), ('other', 'Other')], help_text='Mode of transportation used for the order.', max_length=20, verbose_name='shipping method'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('shipped', 'In transit'), ('customs', 'At customs'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', help_text='Current state of the purchase workflow.', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Supplier that is selling the vehicles in this order.', on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Net value of this line in the selected currency.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('USD', 'USD'), ('EUR', 'EUR'), ('AED', 'AED'), ('PKR', 'PKR'), ('IRR', 'IRR')], default='AFN', help_text='Currency used to price this line.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='description',
            field=models.CharField(help_text='Short description of the item, lot, or service being purchased.', max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='order',
            field=models.ForeignKey(help_text='Purchase order this line belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchaseorder', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='purchaseorderline',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle linked to this line, if the order includes a specific unit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='vehicles.vehicle', verbose_name='vehicle'),
        ),
    ]
