# Generated by Django 5.2.17 on 2026-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_alter_historicalpurchaseorder_bill_of_lading_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchaseorder',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Date by which the supplier expects this order to be paid.', null=True, verbose_name='payment due date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Date by which the supplier expects this order to be paid.', null=True, verbose_name='payment due date'),
        ),
    ]
