# Generated by Django 5.2.17 on 2026-08-18 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organizations.organization', verbose_name='company')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_branch_name_per_company')],
            },
        ),
    ]
