# Generated by Django 5.2.17 on 2026-08-30 20:26

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='code')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization', verbose_name='company')),
            ],
            options={
                'verbose_name': 'expense category',
                'verbose_name_plural': 'expense categories',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='unique_expense_category_name_per_company')],
            },
            bases=(apps.core.models.CompanyConsistencyMixin, models.Model),
        ),
    ]
