# Generated by Django 5.2.17 on 2026-09-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('company', 'code'), name='unique_expense_category_code_per_company'),
        ),
    ]
